// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_cosmic_context from "./routes/api/cosmic-context.ts";
import * as $api_horoscope from "./routes/api/horoscope.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $thanks from "./routes/thanks.tsx";
import * as $AboutModal from "./islands/AboutModal.tsx";
import * as $BackgroundCanvas from "./islands/BackgroundCanvas.tsx";
import * as $BackgroundEffects from "./islands/BackgroundEffects.tsx";
import * as $HomeIsland from "./islands/HomeIsland.tsx";
import * as $HoroscopeDisplay from "./islands/HoroscopeDisplay.tsx";
import * as $InstallPrompt from "./islands/InstallPrompt.tsx";
import * as $KofiModal from "./islands/KofiModal.tsx";
import * as $TabSwitcher from "./islands/TabSwitcher.tsx";
import * as $ThemeIsland from "./islands/ThemeIsland.tsx";
import * as $WelcomeChecker from "./islands/WelcomeChecker.tsx";
import * as $WelcomeModal from "./islands/WelcomeModal.tsx";
import * as $ZodiacPicker from "./islands/ZodiacPicker.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/cosmic-context.ts": $api_cosmic_context,
    "./routes/api/horoscope.ts": $api_horoscope,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/thanks.tsx": $thanks,
  },
  islands: {
    "./islands/AboutModal.tsx": $AboutModal,
    "./islands/BackgroundCanvas.tsx": $BackgroundCanvas,
    "./islands/BackgroundEffects.tsx": $BackgroundEffects,
    "./islands/HomeIsland.tsx": $HomeIsland,
    "./islands/HoroscopeDisplay.tsx": $HoroscopeDisplay,
    "./islands/InstallPrompt.tsx": $InstallPrompt,
    "./islands/KofiModal.tsx": $KofiModal,
    "./islands/TabSwitcher.tsx": $TabSwitcher,
    "./islands/ThemeIsland.tsx": $ThemeIsland,
    "./islands/WelcomeChecker.tsx": $WelcomeChecker,
    "./islands/WelcomeModal.tsx": $WelcomeModal,
    "./islands/ZodiacPicker.tsx": $ZodiacPicker,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
